spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7783016
    username: sql7783016
    password: mZGLA2VX53
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5      
      maximum-pool-size: 10  
      idle-timeout: 300000   
      max-lifetime: 1800000 
      connection-timeout: 30000 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: mariiasthh@gmail.com
    password: hnqhqvuublqgbpwn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
